import "@/styles/globals.css";

import { TRPCReactProvider } from "@/trpc/react";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { Navbar } from "./_components/navbar";
import { ThemeProvider } from "./_components/theme-provider";
const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`font-sans ${inter.variable} min-h-screen w-full`}>
                <TRPCReactProvider cookies={cookies().toString()}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <div className="w-full h-full">
                            <Navbar />
                            {children}
                        </div>
                    </ThemeProvider>
                </TRPCReactProvider>
        </body>
        </html >
    );
}
