import "@/styles/globals.css";

import { Manrope } from "next/font/google";
import { cookies } from "next/headers";
import { Shell } from "@/components/layout";
import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/toaster";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${manrope.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <Shell>
            {children}
          </Shell>
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
