/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RBxQOt18TSN
 */
import Header from "@/components/sidebar/header"
import Navbar from "@/components/sidebar/navbar"

export async function AppShell() {
  return (
    <div className="fixed top-0 w-full flex flex-col h-screen overflow-hidden">
      <Header />
      <Navbar />
    </div>
  )
}
